Fix Error: Undefined method or attribute `set_patch_url' on `node'
NoMethodError: Undefined method or attribute `set_patch_url' on `node'

This reverts commit 3286a001c3ba139fc9256f83755e2c6316131d6f.